### ISSUE TITLE
Unrecognized options "app_id, secret_id" under "pcb_social_login.twitter"

### ISSUE THREAD

**Issue by Codeperitus** [phpcodebooster/social-login#1]
# app/config/config.yml

pcb_social_login:
    model_alias: FlyUserBundle         # your bundle alias
    model_namespace: Fly\UserBundle\Entity      # your entity namespace
    login_path: fos_user_security_login     # route to your login page
    twitter:
       app_id: TWITTER_APP_ID
       secret_id: TWITTER_APP_SECRET_ID

**Comment by phpcodebooster** [comment]
copy and paste all of the following options and replace only one you need

pcb_social_login:
    model_alias: BlogBundle			# your bundle alias
    model_namespace: BlogBundle\Entity		# your entity namespace
    login_path: fos_user_security_login		# route to your login page
    facebook:
       app_id: FACEBOOK_APP_ID
       secret_id: FACEBOOK_APP_SECRET_ID
    twitter:
       app_id: TWITTER_APP_ID
       secret_id: TWITTER_APP_SECRET_ID
    linkedin:
       app_id: LINKEDIN_APP_ID
       secret_id: LINKEDIN_APP_SECRET_ID
    google:
       app_id: GOOGLE_APP_ID
       secret_id: GOOGLE_APP_SECRET_ID

**Comment by phpcodebooster** [comment]
seems like it is an issue with tabs or spaces in the yml file make sure you follow the format shown here: http://www.phpcodebooster.com/post/12/symfony2-social-login-plugin/ or still have problem email on sandip254@gmail.com and I will be helping you online
